version: '3'

services:
  swabinfo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '/home/ubuntu/swabinfo:/app/swabinfo'
      - '/home/ubuntu/files:/app/files'
    working_dir: /app/swabinfo
    restart: unless-stopped
